<a href="https://colab.research.google.com/github/mknair75/machine_learning/blob/main/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import tensorflow as tf 

numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant (numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tf.size(rank_4_tensor)

print ("Number of dimensions", rank_4_tensor.ndim)
print ("Shape", rank_4_tensor.shape)
print ("Elements along first axis", rank_4_tensor.shape[0])
print ("Elements along last axis", rank_4_tensor.shape[-1])
print ("Number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Number of dimensions 4
Shape (2, 3, 4, 5)
Elements along first axis 2
Elements along last axis 5
Number of elements in our tensor 120


In [ ]:
#First element of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# First element from each dimension except for the last one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                             [4,5]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get last item for each row 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

In [ ]:
# Add extra dimension 
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
# Expand the 0th axis 
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  5]]], dtype=int32)>

In [ ]:
# Matrix Multiplication 
tf.matmul(rank_2_tensor,rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 105],
       [ 60,  53]], dtype=int32)>

In [ ]:
rank_2_tensor * rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 16,  25]], dtype=int32)>

In [ ]:
rank_2_tensor @ rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 105],
       [ 60,  53]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2,3],
                  [3,4,5]])
Y= tf.constant([[1,2],[2,3],[3,4]])
X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>)

In [ ]:
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [26, 38]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(X,shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 23],
       [35, 43]], dtype=int32)>

In [ ]:
tf.reshape(X,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 3],
       [4, 5]], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(1,100,50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([56, 57,  6, 67, 63, 29, 70, 85, 32, 41,  9, 88, 29, 64,  5,  7,  9,
       66, 72, 80, 95, 47, 18, 64, 89, 26, 14, 18, 90, 23, 48, 86, 63, 99,
       83, 96, 39, 23, 96,  2,  5,  1, 38, 39, 84, 55, 11, 17, 66, 32])>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2402>

In [ ]:

tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=942.4384>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.69916>

In [ ]:
#tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.25805342, 0.58349764, 0.74955046, 0.0552752 , 0.9363142 ,
       0.20974171, 0.42598283, 0.9570861 , 0.9285284 , 0.19709408,
       0.21411097, 0.23533309, 0.52356315, 0.43090093, 0.51309276,
       0.21002054, 0.30223882, 0.11029756, 0.2231909 , 0.5595106 ,
       0.41658092, 0.36236727, 0.47396386, 0.02919173, 0.8824407 ,
       0.6083511 , 0.73866355, 0.00391126, 0.10795379, 0.07900786,
       0.44614303, 0.46535993, 0.5528556 , 0.6056287 , 0.05835581,
       0.19198596, 0.70219326, 0.6148578 , 0.4737078 , 0.38879526,
       0.63350964, 0.10412621, 0.22663486, 0.0242362 , 0.30637515,
       0.3205247 , 0.795843  , 0.07466996, 0.15476525, 0.5742471 ],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9570861>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.003911257>

In [ ]:
F = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))

In [ ]:
F

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.04243696, 0.8851373 , 0.08538938, 0.8140296 , 0.20480585,
          0.62779045, 0.901513  , 0.99519193, 0.4207009 , 0.22008038,
          0.9671608 , 0.32904947, 0.8153496 , 0.8897246 , 0.94835925,
          0.78874993, 0.7686198 , 0.88702595, 0.7265632 , 0.36882663,
          0.32022882, 0.96221995, 0.7707509 , 0.07917464, 0.3471576 ,
          0.32097983, 0.18635666, 0.4519521 , 0.8484278 , 0.5145216 ,
          0.03791988, 0.16871202, 0.17489076, 0.07419372, 0.99978435,
          0.29314935, 0.4076401 , 0.81951547, 0.62446487, 0.65433896,
          0.22750294, 0.21583557, 0.22751427, 0.33335948, 0.6457648 ,
          0.8322991 , 0.29098654, 0.04095936, 0.25626075, 0.357468  ]]]],
      dtype=float32)>

In [ ]:
F_squezed = tf.squeeze(F)

In [ ]:
F_squezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.04243696, 0.8851373 , 0.08538938, 0.8140296 , 0.20480585,
       0.62779045, 0.901513  , 0.99519193, 0.4207009 , 0.22008038,
       0.9671608 , 0.32904947, 0.8153496 , 0.8897246 , 0.94835925,
       0.78874993, 0.7686198 , 0.88702595, 0.7265632 , 0.36882663,
       0.32022882, 0.96221995, 0.7707509 , 0.07917464, 0.3471576 ,
       0.32097983, 0.18635666, 0.4519521 , 0.8484278 , 0.5145216 ,
       0.03791988, 0.16871202, 0.17489076, 0.07419372, 0.99978435,
       0.29314935, 0.4076401 , 0.81951547, 0.62446487, 0.65433896,
       0.22750294, 0.21583557, 0.22751427, 0.33335948, 0.6457648 ,
       0.8322991 , 0.29098654, 0.04095936, 0.25626075, 0.357468  ],
      dtype=float32)>

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4,on_value="Manoj",off_value="Vineetha")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Manoj', b'Vineetha', b'Vineetha', b'Vineetha'],
       [b'Vineetha', b'Manoj', b'Vineetha', b'Vineetha'],
       [b'Vineetha', b'Vineetha', b'Manoj', b'Vineetha'],
       [b'Vineetha', b'Vineetha', b'Vineetha', b'Manoj']], dtype=object)>

In [ ]:
rand1 = tf.random.uniform((3,3),0,10, dtype = tf.int32)
rand1


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 3, 2],
       [6, 1, 8],
       [1, 0, 8]], dtype=int32)>